print("My name is Jessica Bonnie Ayomide")
print("JJJJJJJJJJJJJ     BBBBBBBBBB       A")
print("            J     B         B     A  A")
print("            J     B          B   A    A")
print("            J     B          B  A      A")
print("            J     B         B  A        A")
print("            J     BBBBBBBBBB   AAAAAAAAAA")
print("            J     B         B  A        A")
print("            J     B          B A        A")
print("J           J     B          B A        A")
print("  J       J       B         B  A        A")
print("    JJJJJ         BBBBBBBBBB   A        A")
